[package]
name = "le_rovine_perdute_rs"
version = "0.1.0"
authors = ["Fabio Lusha <f.lusha@studenti.unibs.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
